name: ci-golang
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-app:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: ["1.17.6", "1.16.5", "1.15.13"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: ${{ matrix.go }}
      - run: go test ./...